# Generated by Django 2.1 on 2018-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookracks', '0003_auto_20180816_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='bookracks.Author'),
        ),
    ]
