# Generated by Django 2.1 on 2018-08-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookracks', '0004_auto_20180816_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_rack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookracks.BookRack'),
            preserve_default=False,
        ),
    ]
