# Generated by Django 2.1 on 2018-08-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookracks', '0005_book_book_rack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.CharField(max_length=50),
        ),
    ]
